### ISSUE TITLE
add_busy_spinner will also be updated during the header update in shinydashboard

### ISSUE THREAD

**Issue by LuShuYangMing** [dreamRs/shinybusy#16]
I just want to show busy_spinner at the beginning of the shiny first loading. However, the busy_spinner could also be shown during the shinydashboard header updating. Below code is an example

```
library(shiny)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(dropdownMenuOutput("notif")),
  dashboardSidebar(),
  dashboardBody(shinybusy::add_busy_spinner(spin = "atom",position = "full-page"))
)

server <- function(input, output) { 
  values<-reactiveValues()
  values[["numvotes"]] <- 1
  Sys.sleep(3)#>>>>>>>>>>>>>>Simulate the shiny first loading process
  output$notif <- renderMenu({
    invalidateLater(5000)
    Sys.sleep(1)#>>>>>>>>>>>>>>suppose there will run something and may take one second
    dropdownMenu(type = "notifications", 
                 badgeStatus = "warning", 
                 notificationItem(icon = icon("ok", lib = "glyphicon"), status = "danger",
                                  paste(values[["numvotes"]], "vote(s)")))
  })
}

shinyApp(ui, server)
```

@pvictor  Thank you very much!

**Comment by pvictor** [comment]
What behavior did you expect ?
For me, spinner is shown at start and then each time `renderMenu` is invalidated.

**Comment by LuShuYangMing** [comment]
I want the spinner is shown only at start, and then never show it. If you run that code, open the shiny and wait for about 5 seconds later, the spinner will be shown again.

**Comment by pvictor** [comment]
Thanks for the complement, you can use `busy_start_up` instead of `add_busy_spinner`:

```r
shinybusy::busy_start_up(
  loader = shinybusy::spin_epic("atom", color = "#FFF"),
  text = "Loading...",
  mode = "timeout",
  timeout = 1500,
  color = "#FFF",
  background = "#112446"
)
```

Spinner will only be shown at application start-up. There's 3 modes available : 

* **timeout**: Busy indicator will be removed after the time (in milliseconds) specified in timeout.
* **manual**: Busy indicator will be removed with `remove_start_up` from server, timeout from busy_start_up is ignored in favor of that of remove_start_up.
* **auto**: Busy indicator is removed after JavaScript `shiny:idle` is triggered for the first time, timeout is taken into account.

Victor

**Comment by LuShuYangMing** [comment]
That's Great! Thank you very much! I neglect this function but pay more attention to `add_busy_spinner`

**Comment by LuShuYangMing** [comment]
That's Great! Thank you very much! I neglect this function but pay more attention to `add_busy_spinner`
